title: Ashish Kumar Maindola's GitHub Page
description: Personal website of Ashish Kumar Maindola, PhD physics student at Ahmedabad University
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://your-username.github.io" # the base hostname & protocol for your site
